### ISSUE TITLE
API and Front end changes for EHR data

### ISSUE THREAD

**Issue by jeet-vora** [clinical-biomarkers/biomarker-issue-repo#253]
@ReneRanzinger 

<img width="996" height="409" alt="Image" src="https://github.com/user-attachments/assets/df3b628a-937a-46e0-b145-9437401a4640" />

**Comment by ReneRanzinger** [comment]
This would be my proposed addition to the biomarker details service:

```
{
  "normal_ranges": [
    {
      "entity": "Some Entity",
      "source": [
        {
          "source_name": "GW",
          "ranges": [
            {
              "age": "20-29",
              "sex": "male",
              "more_stuff": "..."
            },
            {
              "age": "20-29",
              "sex": "male",
              "more_stuff": "..."
            }
          ]
        },
        {
          "source_name": "some other source",
          "ranges": [
            {
              "age": "20-29",
              "sex": "male",
              "more_stuff": "..."
            }
          ]
        }
      ]
    },
    {
      "entity": "Some other entity",
      "source": [
        {
          "source_name": "GW",
          "ranges": [
            {
              "age": "20-29",
              "sex": "male",
              "more_stuff": "..."
            }
          ]
        }
      ]
    }
  ]
}
```

@sujeetvkulkarni if you want to change the nesting to have entity inside source please change it but I think it works better this way since Raja said its more like to just have one entity.

**Comment by rykahsay** [comment]
@jeet-vora --- looks like you have not created "/data/shared/biomarkerdb/releases/data/v-y.y.y/compiled/entity_normalranges_oracle_health.csv" using "/data/shared/biomarkerdb/releases/data/v-y.y.y/reviewed/entity_normalranges_oracle_health.csv", and the compiled file will have the additional fields we discussed in it. You are blocking me.

**Comment by jeet-vora** [comment]
@rykahsay 
The file has been added `/data/shared/biomarkerdb/releases/data/v-y.y.y/compiled/entity_normalranges_oracle_health.csv`

Please note the headers in the file and the proposed headers are slightly different e.g age_group (in file) vs age (api service / frontend)

**Comment by rykahsay** [comment]
Instructions for Maria on how to update the JSON files to be loaded to MongoDB

commands
```
$ cd /software/biomarkerdb/object-maker/
$ python3 update-biomarker-objects.py
```

The script "update-biomarker-objects.py" depends in the config file "/software/biomarkerdb/object-maker/conf/config.json" which specifies the input and output folders of the script


Contents of "/software/biomarkerdb/object-maker/conf/config.json"
```
{
	"normalrangesdb":"/data/shared/biomarkerdb/releases/data/v-y.y.y/jsondb/normalrangesdb/",
	"biomarkerdb":"/data/shared/biomarkerdb/generated/datamodel/merged/current/merged_json/",
	"biomarkerdb_updated":"/data/shared/biomarkerdb/generated/datamodel/merged/current/merged_json_updated/"
}
```

As you can easily understand, what the script does is load JSON files from your "merged_json/" directory and normal range objects from "normalrangesdb" and creates updated biomarker detail JSON objects under "merged_json_updated/". 

You will need to run this script before you update or load biomarker detail JSON objects into MongoDB (and JSON objects you load to MongoDB should be from "merged_json_updated/")

**Comment by rykahsay** [comment]
@jeet-vora 
It looks like none of the entities/proteins is repeating.

For example, there is only one row for "P45380" -- how is the frontend going to show boxes for male/female for this entity_id?

$ cat compiled/entity_normalranges_oracle_health.csv | grep P45380
```
P45380,"Troponin T, cardiac muscle",Troponin T S/Pl,20-29,Female,ng/mL,0.011,0.06,0.025083333,0.014368263,0.02,0.02,0.02,12
```


This is true for all entities in the file -- none of the proteins/entities repeats (has more than one row)
```
$ cat compiled/entity_normalranges_oracle_health.csv | awk -F, '{print $1}' |wc
     38      38     272
$ cat compiled/entity_normalranges_oracle_health.csv | awk -F, '{print $1}' |sort -u |wc
     38      38     272
```

**Comment by jeet-vora** [comment]
@rykahsay 

The file has been corrected. It was a formatting error. There are only two protein and entities for this sample data - P19429 | P45379.

**Comment by rykahsay** [comment]
@jeet-vora ... the file is still the same. Look at the first column, there is more than one entity IDs (proteins). This is taking too much time given the time line we agreed on.


$ cat /data/shared/biomarkerdb/releases/data/v-y.y.y/compiled/entity_normalranges_oracle_health.csv

```
entity_id,entity_name,entity_name_src,age_grp,sex,units,min,max,mean_val,sd_val,q1,median_val,q3,n_val
P19429,"Troponin I, cardiac muscle",Troponin I,00-09,Female,ng/mL,0.228,0.228,0.228,NA,0.228,0.228,0.228,1
P19430,"Troponin I, cardiac muscle",Troponin I,00-09,Male,ng/mL,0.015,0.309,0.14225,0.101926794,0.07925,0.135,0.20525,8
P19431,"Troponin I, cardiac muscle",Troponin I,10-19,Female,ng/mL,0.015,0.07,0.023046154,0.012281122,0.015,0.017,0.03,65
P19432,"Troponin I, cardiac muscle",Troponin I,10-19,Male,ng/mL,0.015,0.34,0.043111111,0.069813948,0.015,0.02,0.04,36
P19433,"Troponin I, cardiac muscle",Troponin I,20-29,Female,ng/mL,0.012,0.3,0.026082051,0.035122957,0.015,0.015,0.0245,195
P19434,"Troponin I, cardiac muscle",Troponin I,20-29,Male,ng/mL,0.011,0.354,0.0385,0.054617397,0.015,0.017,0.04,184
P19435,"Troponin I, cardiac muscle",Troponin I,30-39,Female,ng/mL,0.012,0.3,0.031068677,0.041539425,0.015,0.017,0.04,597
P19436,"Troponin I, cardiac muscle",Troponin I,30-39,Male,ng/mL,0.011,0.352,0.039156126,0.058936325,0.015,0.02,0.04,506
P19437,"Troponin I, cardiac muscle",Troponin I,40-49,Female,ng/mL,0.011,0.336,0.029675758,0.035995266,0.015,0.017,0.04,990
P19438,"Troponin I, cardiac muscle",Troponin I,40-49,Male,ng/mL,0.011,0.301,0.037662324,0.04662144,0.015,0.02,0.04,921
P19439,"Troponin I, cardiac muscle",Troponin I,50-59,Female,ng/mL,0.011,0.354,0.031459362,0.044530973,0.015,0.017,0.03,1661
P19440,"Troponin I, cardiac muscle",Troponin I,50-59,Male,ng/mL,0.011,0.344,0.038927786,0.055739909,0.015,0.02,0.04,1274
P19441,"Troponin I, cardiac muscle",Troponin I,60-69,Female,ng/mL,0.011,0.349,0.043784019,0.061808007,0.016,0.02,0.04,1727
P19442,"Troponin I, cardiac muscle",Troponin I,60-69,Male,ng/mL,0.011,0.34,0.043496154,0.054556541,0.02,0.02,0.04,1820
P19443,"Troponin I, cardiac muscle",Troponin I,70-79,Female,ng/mL,0.011,0.358,0.041804295,0.05847919,0.02,0.02,0.04,2049
P19444,"Troponin I, cardiac muscle",Troponin I,70-79,Male,ng/mL,0.011,0.354,0.050257906,0.065228843,0.02,0.021,0.046,1423
P19445,"Troponin I, cardiac muscle",Troponin I,80-89,Female,ng/mL,0.011,0.35,0.046264176,0.062788748,0.02,0.02,0.04,1499
P19446,"Troponin I, cardiac muscle",Troponin I,80-89,Male,ng/mL,0.011,0.359,0.050288577,0.063360228,0.02,0.026,0.04375,998
P19447,"Troponin I, cardiac muscle",Troponin I,90+,Female,ng/mL,0.011,0.331,0.054653226,0.065498122,0.02,0.036,0.05,620
P19448,"Troponin I, cardiac muscle",Troponin I,90+,Male,ng/mL,0.011,0.359,0.061860558,0.070521263,0.02,0.033,0.065,251
P45379,"Troponin T, cardiac muscle",Troponin T S/Pl,10-19,Female,ng/mL,0.02,0.02,0.02,NA,0.02,0.02,0.02,1
P45380,"Troponin T, cardiac muscle",Troponin T S/Pl,20-29,Female,ng/mL,0.011,0.06,0.025083333,0.014368263,0.02,0.02,0.02,12
P45381,"Troponin T, cardiac muscle",Troponin T S/Pl,20-29,Male,ng/mL,0.011,0.06,0.0284,0.022157015,0.011,0.02,0.05,10
P45382,"Troponin T, cardiac muscle",Troponin T S/Pl,30-39,Female,ng/mL,0.011,0.06,0.023409091,0.012481276,0.02,0.02,0.0225,44
P45383,"Troponin T, cardiac muscle",Troponin T S/Pl,30-39,Male,ng/mL,0.012,0.07,0.033580645,0.018927536,0.02,0.02,0.0525,31
P45384,"Troponin T, cardiac muscle",Troponin T S/Pl,40-49,Female,ng/mL,0.011,0.07,0.023706667,0.012854459,0.014,0.02,0.028,75
P45385,"Troponin T, cardiac muscle",Troponin T S/Pl,40-49,Male,ng/mL,0.011,0.075,0.025115385,0.013009279,0.02,0.02,0.03,52
P45386,"Troponin T, cardiac muscle",Troponin T S/Pl,50-59,Female,ng/mL,0.011,0.07,0.024470588,0.013589179,0.02,0.02,0.03,136
P45387,"Troponin T, cardiac muscle",Troponin T S/Pl,50-59,Male,ng/mL,0.011,0.07,0.031263158,0.017351489,0.02,0.02,0.05,133
P45388,"Troponin T, cardiac muscle",Troponin T S/Pl,60-69,Female,ng/mL,0.011,0.076,0.027619512,0.015693811,0.02,0.02,0.031,205
P45389,"Troponin T, cardiac muscle",Troponin T S/Pl,60-69,Male,ng/mL,0.011,0.079,0.029858065,0.018038357,0.02,0.02,0.04,155
P45390,"Troponin T, cardiac muscle",Troponin T S/Pl,70-79,Female,ng/mL,0.011,0.07,0.024477273,0.014437631,0.01275,0.02,0.03,176
P45391,"Troponin T, cardiac muscle",Troponin T S/Pl,70-79,Male,ng/mL,0.011,0.075,0.028454545,0.014418592,0.02,0.021,0.036,165
P45392,"Troponin T, cardiac muscle",Troponin T S/Pl,80-89,Female,ng/mL,0.011,0.07,0.026655367,0.013597288,0.02,0.02,0.03,177
P45393,"Troponin T, cardiac muscle",Troponin T S/Pl,80-89,Male,ng/mL,0.011,0.07,0.028045752,0.014180852,0.02,0.02,0.03,153
P45394,"Troponin T, cardiac muscle",Troponin T S/Pl,90+,Female,ng/mL,0.013,0.077,0.032515152,0.017294781,0.02,0.028,0.04,99
P45395,"Troponin T, cardiac muscle",Troponin T S/Pl,90+,Male,ng/mL,0.012,0.07,0.034039474,0.016473365,0.02,0.03,0.041,76
```

**Comment by jeet-vora** [comment]
@rykahsay 

Apologies. I have now checked and verified - /data/shared/biomarkerdb/releases/data/v-y.y.y/compiled/entity_normalranges_oracle_health.csv

<img width="585" height="623" alt="Image" src="https://github.com/user-attachments/assets/3f806ea4-15e5-48b7-a2e3-4a649bf493a6" />

**Comment by rykahsay** [comment]
@ReneRanzinger @sujeetvkulkarni  ... given below is entity EHR normal ranges data for entities (UPKB:P19429 in this case) and @mariacuria will run the script I created for her (see one of the above comments) to inject this into the biomarker detail JSON objects in a new section called "entity_normal_ranges"


Section "entity_normal_ranges" injected into biomarker detail JSON objects which
```
{
    "biomarker_id": "AN6373-1",
    ...
    "entity_normal_ranges":[]
    ...
}
```

$ cat jsondb/normalrangesdb/UPKB.P19429.json 
```
{
    "entity_name": "Troponin I, cardiac muscle",
    "entity_id": "UPKB:P19429",
    "source": [
        {
            "source_name": "Oracle Health",
            "ranges": [
                {
                    "age_grp": "00-09",
                    "sex": "Male",
                    "mean_val": 0.1422,
                    "median_val": 0.135,
                    "sd_val": 0.1019,
                    "min": 0.015,
                    "max": 0.309,
                    "q1": 0.0793,
                    "q3": 0.2052,
                    "n_val": 8,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "10-19",
                    "sex": "Female",
                    "mean_val": 0.023,
                    "median_val": 0.017,
                    "sd_val": 0.0123,
                    "min": 0.015,
                    "max": 0.07,
                    "q1": 0.015,
                    "q3": 0.03,
                    "n_val": 65,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "10-19",
                    "sex": "Male",
                    "mean_val": 0.0431,
                    "median_val": 0.02,
                    "sd_val": 0.0698,
                    "min": 0.015,
                    "max": 0.34,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 36,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "20-29",
                    "sex": "Female",
                    "mean_val": 0.0261,
                    "median_val": 0.015,
                    "sd_val": 0.0351,
                    "min": 0.012,
                    "max": 0.3,
                    "q1": 0.015,
                    "q3": 0.0245,
                    "n_val": 195,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "20-29",
                    "sex": "Male",
                    "mean_val": 0.0385,
                    "median_val": 0.017,
                    "sd_val": 0.0546,
                    "min": 0.011,
                    "max": 0.354,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 184,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "30-39",
                    "sex": "Female",
                    "mean_val": 0.0311,
                    "median_val": 0.017,
                    "sd_val": 0.0415,
                    "min": 0.012,
                    "max": 0.3,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 597,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "30-39",
                    "sex": "Male",
                    "mean_val": 0.0392,
                    "median_val": 0.02,
                    "sd_val": 0.0589,
                    "min": 0.011,
                    "max": 0.352,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 506,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "40-49",
                    "sex": "Female",
                    "mean_val": 0.0297,
                    "median_val": 0.017,
                    "sd_val": 0.036,
                    "min": 0.011,
                    "max": 0.336,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 990,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "40-49",
                    "sex": "Male",
                    "mean_val": 0.0377,
                    "median_val": 0.02,
                    "sd_val": 0.0466,
                    "min": 0.011,
                    "max": 0.301,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 921,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "50-59",
                    "sex": "Female",
                    "mean_val": 0.0315,
                    "median_val": 0.017,
                    "sd_val": 0.0445,
                    "min": 0.011,
                    "max": 0.354,
                    "q1": 0.015,
                    "q3": 0.03,
                    "n_val": 1661,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "50-59",
                    "sex": "Male",
                    "mean_val": 0.0389,
                    "median_val": 0.02,
                    "sd_val": 0.0557,
                    "min": 0.011,
                    "max": 0.344,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 1274,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "60-69",
                    "sex": "Female",
                    "mean_val": 0.0438,
                    "median_val": 0.02,
                    "sd_val": 0.0618,
                    "min": 0.011,
                    "max": 0.349,
                    "q1": 0.016,
                    "q3": 0.04,
                    "n_val": 1727,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "60-69",
                    "sex": "Male",
                    "mean_val": 0.0435,
                    "median_val": 0.02,
                    "sd_val": 0.0546,
                    "min": 0.011,
                    "max": 0.34,
                    "q1": 0.02,
                    "q3": 0.04,
                    "n_val": 1820,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "70-79",
                    "sex": "Female",
                    "mean_val": 0.0418,
                    "median_val": 0.02,
                    "sd_val": 0.0585,
                    "min": 0.011,
                    "max": 0.358,
                    "q1": 0.02,
                    "q3": 0.04,
                    "n_val": 2049,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "70-79",
                    "sex": "Male",
                    "mean_val": 0.0503,
                    "median_val": 0.021,
                    "sd_val": 0.0652,
                    "min": 0.011,
                    "max": 0.354,
                    "q1": 0.02,
                    "q3": 0.046,
                    "n_val": 1423,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "80-89",
                    "sex": "Female",
                    "mean_val": 0.0463,
                    "median_val": 0.02,
                    "sd_val": 0.0628,
                    "min": 0.011,
                    "max": 0.35,
                    "q1": 0.02,
                    "q3": 0.04,
                    "n_val": 1499,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "80-89",
                    "sex": "Male",
                    "mean_val": 0.0503,
                    "median_val": 0.026,
                    "sd_val": 0.0634,
                    "min": 0.011,
                    "max": 0.359,
                    "q1": 0.02,
                    "q3": 0.0437,
                    "n_val": 998,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "90+",
                    "sex": "Female",
                    "mean_val": 0.0547,
                    "median_val": 0.036,
                    "sd_val": 0.0655,
                    "min": 0.011,
                    "max": 0.331,
                    "q1": 0.02,
                    "q3": 0.05,
                    "n_val": 620,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "90+",
                    "sex": "Male",
                    "mean_val": 0.0619,
                    "median_val": 0.033,
                    "sd_val": 0.0705,
                    "min": 0.011,
                    "max": 0.359,
                    "q1": 0.02,
                    "q3": 0.065,
                    "n_val": 251,
                    "units": "ng/mL"
                }
            ]
        },
        {
            "source_name": "GWDC",
            "ranges": [
                {
                    "age_grp": "00-09",
                    "sex": "Male",
                    "mean_val": 0.1422,
                    "median_val": 0.135,
                    "sd_val": 0.1019,
                    "min": 0.015,
                    "max": 0.309,
                    "q1": 0.0793,
                    "q3": 0.2052,
                    "n_val": 8,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "10-19",
                    "sex": "Female",
                    "mean_val": 0.023,
                    "median_val": 0.017,
                    "sd_val": 0.0123,
                    "min": 0.015,
                    "max": 0.07,
                    "q1": 0.015,
                    "q3": 0.03,
                    "n_val": 65,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "10-19",
                    "sex": "Male",
                    "mean_val": 0.0431,
                    "median_val": 0.02,
                    "sd_val": 0.0698,
                    "min": 0.015,
                    "max": 0.34,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 36,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "20-29",
                    "sex": "Female",
                    "mean_val": 0.0261,
                    "median_val": 0.015,
                    "sd_val": 0.0351,
                    "min": 0.012,
                    "max": 0.3,
                    "q1": 0.015,
                    "q3": 0.0245,
                    "n_val": 195,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "20-29",
                    "sex": "Male",
                    "mean_val": 0.0385,
                    "median_val": 0.017,
                    "sd_val": 0.0546,
                    "min": 0.011,
                    "max": 0.354,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 184,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "30-39",
                    "sex": "Female",
                    "mean_val": 0.0311,
                    "median_val": 0.017,
                    "sd_val": 0.0415,
                    "min": 0.012,
                    "max": 0.3,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 597,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "30-39",
                    "sex": "Male",
                    "mean_val": 0.0392,
                    "median_val": 0.02,
                    "sd_val": 0.0589,
                    "min": 0.011,
                    "max": 0.352,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 506,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "40-49",
                    "sex": "Female",
                    "mean_val": 0.0297,
                    "median_val": 0.017,
                    "sd_val": 0.036,
                    "min": 0.011,
                    "max": 0.336,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 990,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "40-49",
                    "sex": "Male",
                    "mean_val": 0.0377,
                    "median_val": 0.02,
                    "sd_val": 0.0466,
                    "min": 0.011,
                    "max": 0.301,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 921,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "50-59",
                    "sex": "Female",
                    "mean_val": 0.0315,
                    "median_val": 0.017,
                    "sd_val": 0.0445,
                    "min": 0.011,
                    "max": 0.354,
                    "q1": 0.015,
                    "q3": 0.03,
                    "n_val": 1661,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "50-59",
                    "sex": "Male",
                    "mean_val": 0.0389,
                    "median_val": 0.02,
                    "sd_val": 0.0557,
                    "min": 0.011,
                    "max": 0.344,
                    "q1": 0.015,
                    "q3": 0.04,
                    "n_val": 1274,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "60-69",
                    "sex": "Female",
                    "mean_val": 0.0438,
                    "median_val": 0.02,
                    "sd_val": 0.0618,
                    "min": 0.011,
                    "max": 0.349,
                    "q1": 0.016,
                    "q3": 0.04,
                    "n_val": 1727,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "60-69",
                    "sex": "Male",
                    "mean_val": 0.0435,
                    "median_val": 0.02,
                    "sd_val": 0.0546,
                    "min": 0.011,
                    "max": 0.34,
                    "q1": 0.02,
                    "q3": 0.04,
                    "n_val": 1820,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "70-79",
                    "sex": "Female",
                    "mean_val": 0.0418,
                    "median_val": 0.02,
                    "sd_val": 0.0585,
                    "min": 0.011,
                    "max": 0.358,
                    "q1": 0.02,
                    "q3": 0.04,
                    "n_val": 2049,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "70-79",
                    "sex": "Male",
                    "mean_val": 0.0503,
                    "median_val": 0.021,
                    "sd_val": 0.0652,
                    "min": 0.011,
                    "max": 0.354,
                    "q1": 0.02,
                    "q3": 0.046,
                    "n_val": 1423,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "80-89",
                    "sex": "Female",
                    "mean_val": 0.0463,
                    "median_val": 0.02,
                    "sd_val": 0.0628,
                    "min": 0.011,
                    "max": 0.35,
                    "q1": 0.02,
                    "q3": 0.04,
                    "n_val": 1499,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "80-89",
                    "sex": "Male",
                    "mean_val": 0.0503,
                    "median_val": 0.026,
                    "sd_val": 0.0634,
                    "min": 0.011,
                    "max": 0.359,
                    "q1": 0.02,
                    "q3": 0.0437,
                    "n_val": 998,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "90+",
                    "sex": "Female",
                    "mean_val": 0.0547,
                    "median_val": 0.036,
                    "sd_val": 0.0655,
                    "min": 0.011,
                    "max": 0.331,
                    "q1": 0.02,
                    "q3": 0.05,
                    "n_val": 620,
                    "units": "ng/mL"
                },
                {
                    "age_grp": "90+",
                    "sex": "Male",
                    "mean_val": 0.0619,
                    "median_val": 0.033,
                    "sd_val": 0.0705,
                    "min": 0.011,
                    "max": 0.359,
                    "q1": 0.02,
                    "q3": 0.065,
                    "n_val": 251,
                    "units": "ng/mL"
                }
            ]
        }
    ]
}
```

**Comment by rykahsay** [comment]
@mariacuria  ... I am repeating the above comment here. Once you do this, please upload the JSON files under "/data/shared/biomarkerdb/generated/datamodel/merged/current/merged_json_updated/" to MongoDB, and make sure the response in the biomarker detail API contains the new section "entity_normal_ranges" 
for biomarker_id="AN6373-1"




Instructions for Maria on how to update the JSON files to be loaded to MongoDB

commands
```
$ cd /software/biomarkerdb/object-maker/
$ python3 update-biomarker-objects.py
```

The script "update-biomarker-objects.py" depends in the config file "/software/biomarkerdb/object-maker/conf/config.json" which specifies the input and output folders of the script


Contents of "/software/biomarkerdb/object-maker/conf/config.json"
```
{
	"normalrangesdb":"/data/shared/biomarkerdb/releases/data/v-y.y.y/jsondb/normalrangesdb/",
	"biomarkerdb":"/data/shared/biomarkerdb/generated/datamodel/merged/current/merged_json/",
	"biomarkerdb_updated":"/data/shared/biomarkerdb/generated/datamodel/merged/current/merged_json_updated/"
}
```

As you can easily understand, what the script does is load JSON files from your "merged_json/" directory and normal range objects from "normalrangesdb" and creates updated biomarker detail JSON objects under "merged_json_updated/". 

You will need to run this script before you update or load biomarker detail JSON objects into MongoDB (and JSON objects you load to MongoDB should be from "merged_json_updated/")

**Comment by mariacuria** [comment]
Is it going to work fine if I do this before the previous dataset viewer push? 1.0.3 and 1.0.4 dataset viewers have not been pushed due to BCO delays. I remember it created issues with historydb in the past.

Additionally, before I start the push, @jeet-vora and I need to create BCOs for the new datasets in this release (`cgi.tsv` and `mw_loinc_biomarkers.tsv`)

Disregard this comment, the dataset viewer is not going to have changes.

**Comment by jeet-vora** [comment]
@mariacuria 
We will create the dummy ones for now with required info only for this release. Next week we can create the entire BCOs.

**Comment by mariacuria** [comment]
BCOs are done. Pushing 1.0.5 dataset viewer.

**Comment by mariacuria** [comment]
Ran `update-biomarker-objects.py`, initiating the load.
`AN6373-1.json` contains `entity_normal_ranges`.

**Comment by mariacuria** [comment]
Every step in `load_data.py` succeeds up to the cache clearing (the last step). This is the first time I see this exception - not sure how to troubleshoot/solve.
```
2025-10-23 21:02:55,763 INFO Calling /auth/clear_cache...
2025-10-23 21:02:55,781 ERROR Data Load failed, check the logs.
HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /auth/clear_cache (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff7d4ce6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib64/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7eff7d4ce6d0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /auth/clear_cache (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff7d4ce6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/shared/repos/biomarker-backend-api/load/load_data.py", line 416, in <module>
    elapsed_time = main(options=options, server=server)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/load/load_data.py", line 348, in main
    response = requests.post(endpoint, json=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shared/repos/biomarker-backend-api/env/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /auth/clear_cache (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff7d4ce6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by mariacuria** [comment]
Solved by restarting the docker container.

**Comment by mariacuria** [comment]
Done on `dev` server, pushing to `prd`.

<img width="926" height="1086" alt="Image" src="https://github.com/user-attachments/assets/e6cc96aa-ad47-4da6-bcaa-0e29d684ef4c" />

**Comment by mariacuria** [comment]
Loaded to `prd`.

**Comment by rajamazumder** [comment]
@jeet-vora Jeremy sent real data for boxplot already for Troponin the same day I do not see it in this ticket. Also, can we add at the top of the table the mapping of our entity name and what it is called in the EHR? That can be really useful.

**Comment by jeet-vora** [comment]
There is a separate ticket for it

**Comment by ReneRanzinger** [comment]
@mariacuria your example shows age group 0-9 and 10-19. Didnt we agree to filter them out or is that just test data?

**Comment by sujeetvkulkarni** [comment]
@rajamazumder @ReneRanzinger @jeet-vora By what time we need to push front end changes to production?
When will the actual data be pushed to production?

**Comment by mariacuria** [comment]
> [@mariacuria](https://github.com/mariacuria) your example shows age group 0-9 and 10-19. Didnt we agree to filter them out or is that just test data?

I believe @jeet-vora authored the Oracle Health csv input file, I wasn't instructed to filter the age ranges

**Comment by jeet-vora** [comment]
Yes they are in the dataset. We should filter them at the API level.
I didn't specify at the API response but did it at the mockup level.

@mariacuria Can you filter them now? I can remove it from the dataset for now if needed.
@sujeetvkulkarni It seems the current version data is loaded to production. How much time will you need to push to prd?

**Comment by sujeetvkulkarni** [comment]
@jeet-vora I am working on the changes and plan to push it to production early next week.

**Comment by mariacuria** [comment]
> [@mariacuria](https://github.com/mariacuria) Can you filter them now? I can remove it from the dataset for now if needed.

I suppose the filtering can occur within `update-biomarker-objects.py` but will need to consult with Robel on what's best practice here

**Comment by jeet-vora** [comment]
> > [@mariacuria](https://github.com/mariacuria) Can you filter them now? I can remove it from the dataset for now if needed.
> 
> I suppose the filtering can occur within `update-biomarker-objects.py` but will need to consult with Robel on what's best practice here

I have **for now** removed the rows from the dataset in /data/shared/biomarkerdb/releases/data/v-y.y.y/compiled/entity_normalranges_oracle_health.csv

**Comment by jeet-vora** [comment]
@ReneRanzinger @sujeetvkulkarni 

Updated: Example mockup for the showing the data as Box Plot

<img width="490" height="227" alt="Image" src="https://github.com/user-attachments/assets/d8ff7df5-3060-4f4e-a2d8-7da2b4272f56" />

Box = middle 50% of data (Q1 to Q3)
Whiskers = vertical lines extending to min/max non-outlier values
Horizontal bars at whisker ends = caps showing where the whiskers stop
Middle line in box = median
X mark = mean
n = Cohort size

**Comment by mariacuria** [comment]
> I have **for now** removed the rows from the dataset in /data/shared/biomarkerdb/releases/data/v-y.y.y/compiled/entity_normalranges_oracle_health.csv

Thank you, will initiate the new push.

@sujeetvkulkarni if I make changes to the API now, it won't interfere with anything on your side, right?

**Comment by sujeetvkulkarni** [comment]
@mariacuria No, please go ahead.

**Comment by sujeetvkulkarni** [comment]
I have deployed EHR box plot and table changes to the production.
Please have a look at it - https://www.biomarkerkb.org/biomarker/AN6373-1#Entity-Normal-Ranges.

I am filtering age groups - "00-09" and "10-19" from displaying in the table and box plot but they need to be filtered from api.

**Comment by jeet-vora** [comment]
From Sujeet

Hi Raja, Hi Jeet,

I have deployed EHR box plot and table changes to the production.
Please have a look at it - https://www.biomarkerkb.org/biomarker/AN6373-1#Entity-Normal-Ranges.

I am filtering age groups - "00-09" and "10-19" from displaying in the table and box plot but they need to be filtered from api.

Let me know if you have any suggestions.

From Raja

Hi Sujeet,
Great work. This is amazing. Few comments for all cc-ed. Please respond if you agree or disagree to update the formula. I am ok with A. But would prefer B or something similar.

A) I think we should just do IQR box plot or a box-only plot because we want to emphasize the interquartile range (IQR) and median
B) IF we want the upper whisker bar then I think the max is not right in the data and the chart. Jeet/Robel/Jeremy is just cutting off some values from the top (and also maybe from the bottom). Usually, the max is 1.5 time IQR. See below what the max whisker should be.

  | Age Group | Sex | Q1 | Q3 | IQR | 1.5×IQR | Upper Whisker (Max if 1.5×IQR) |
|------------|------|------|------|---------|--------------------------------|
| 20–29 | Female | 0.015 | 0.0245 | 0.0095 | 0.01425 | 0.0388 |
| 20–29 | Male | 0.015 | 0.040 | 0.025 | 0.0375 | 0.0775 |
| 30–39 | Female | 0.015 | 0.040 | 0.025 | 0.0375 | 0.0775 |
| 30–39 | Male | 0.015 | 0.040 | 0.025 | 0.0375 | 0.0775 |  

IQR=Q3−Q1 Upper Whisker Limit=Q3+1.5×IQR

From Jeet

This is great Sujeet.

Yes I think so too we should show the max whisker as 1.5 IQR, we will to do the calculations at our end. Lets discuss this next Tuesday in the meeting.

Also right now we can select both data sources, GWDC and Oracle Health. If there is no data for other source it should be greyed out and unselectable.

<img width="546" height="242" alt="Image" src="https://github.com/user-attachments/assets/04ed5933-b559-4c77-828e-894c539460b3" />

**Comment by jeet-vora** [comment]
If this is done @sujeetvkulkarni please close the ticket or assign it back to me.

**Comment by sujeetvkulkarni** [comment]
@jeet-vora Changes are done from my side. If there are any new changes, please create a new ticket and assign it to me.
I have logged #https://github.com/clinical-biomarkers/biomarker-issue-repo/issues/330 related to duplicate rows.

**Comment by jeet-vora** [comment]
@sujeetvkulkarni Sure Thanks
